# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='colour',
            field=models.CharField(choices=[('white', 'white'), ('yellow', 'yellow'), ('blue', 'blue'), ('green', 'green')], default='white', max_length=20),
        ),
    ]
